### ISSUE TITLE
Compiler error if a serialized struct contains Arc (which is accepted by base postcard serializer)

### ISSUE THREAD

**Issue by Shelim** [teamplayer3/postcard-bindgen#41]
MRE:

```rust
#[derive(Serialize, PostcardBindings)]
pub struct Definition {
    // other fields
}
#[derive(Serialize, PostcardBindings)]
pub struct RegisterNewDefinition{
    id: u64,
    definition: Arc<Definition>,
    // other fields
}
```

This structs will be serialized properly in Postcard, but the BindGen results is:
`⚠ The trait bound 'Arc<Definition>: GenJsBinding' is not satisfied`

I need raw `Definition` around and I would vote against cloning it for the purpose of just serializing it to be send across process via websocket to javascript frontend.

I have also the same problem with `RwLock`

**Comment by teamplayer3** [comment]
Thanks for your issue. I will add these types.

**Comment by teamplayer3** [comment]
Could you check if changes in #42 resolves your issue?
