### ISSUE TITLE
[Bug] Generated JS code is missing break statements when running with no runtime type checks

### ISSUE THREAD

**Issue by planted-sam** [teamplayer3/postcard-bindgen#56]
Hi there, I've been trying to create a simple postcard-bindgen project for making a JS package for compressing data.

I have gotten this to work, though I had to make some manual edits to the generated JS code, and based on what I'm reading in the source code, that shouldn't be needed.

Specifically I noticed that the switch case inside the generated/exported `serialize` was missing break statements after each clause unless I turned runtime type checks back on (which seems to break when used on the JS side for me - though I'm not sure if that's due to me typing something wrong).

### main.js with runtime checks off
```
use postcard_bindgen::{generate_bindings, javascript, PackageInfo, PostcardBindings};
use serde::{Serialize, Deserialize};

// Define structs that will be used for serializing data
#[derive(Serialize, Deserialize, PostcardBindings)]
struct Plant {
    posts: Vec<Post>,
}

#[derive(Serialize, Deserialize, PostcardBindings)]
struct Post {
    id: u32,
    power_plant_revision_id: u32,
    post_part_id: u32,
    hat_part_id: u32,
    loc_lon: f64,
    loc_lat: f64,
    loc_alt: f64,
    quat_w: f64,
    quat_x: f64,
    quat_y: f64,
    quat_z: f64,
    structure_id: String,
    row_id: u32,
    col_id: u32,
    //todo: add undulation fields as options?
}

fn main() {
    // Generate javascript version of package
    javascript::build_package(
        std::env::current_dir().unwrap().as_path(),
        PackageInfo {
            name: "dist-js".into(),
            version: "0.1.0".try_into().unwrap()
        },
        javascript::GenerationSettings::enable_all().runtime_type_checks(false),
        generate_bindings!(Plant, Post)
    ).unwrap();
}
```

### Resulting JS code snippet (just including the module.exports.serialize part, that's what I had to manually edit to get it to work)
```js

module.exports.serialize = (type, value) => {
    if (!(typeof type === "string")) {
        throw "type must be a string"
    }
    const s = new Serializer()
    switch (type) { case "Plant": serialize_PLANT(s, value); case "Post": serialize_POST(s, value) } // should have a `break` after "Plant" case
    return s.finish()
}

```

Adding a break statement manually to the js code works, but is less than ideal. I think this is possibly a bug with how [this function works in the source](https://github.com/teamplayer3/postcard-bindgen/blob/3329c24e28317cda7ae91342892e006997efd6b9/postcard-bindgen-core/src/code_gen/js/ser.rs#L46) though I'm obviously not an expert on this codebase.

FWIW here's what `module.exports.serialize` looks like with runtime checks on (just `GenerationSettings::enable_all()`)
(it does appear to have the correct break statements)
```js
module.exports.serialize = (type, value) => {
    if (!(typeof type === "string")) {
        throw "type must be a string"
    }
    const s = new Serializer()
    switch (type) { case "Plant": if (is_PLANT(value)) { serialize_PLANT(s, value) } else throw "value has wrong format"; break; case "Post": if (is_POST(value)) { serialize_POST(s, value) } else throw "value has wrong format"; break }
    return s.finish()
}
```

Is this an error on my end, or is this a bug in postcard-bindgen's javascript generation?

**Comment by teamplayer3** [comment]
Thanks for opening this issue. I fixed this in a pull request, which was not merged and published yet. I merged it. You can now try the main branch of this crate. Could you give me feedback?

After clementwanjau/tree-ds/issues/22 is done, I can publish a new version to crates.io.

**Comment by planted-sam** [comment]
> Thanks for opening this issue. I fixed this in a pull request, which was not merged and published yet. I merged it. You can now try the main branch of this crate. Could you give me feedback?
> 
> After [clementwanjau/tree-ds/issues/22](https://github.com/clementwanjau/tree-ds/issues/22) is done, I can publish a new version to crates.io.

That worked for me when I used the latest `main`. Output for the exported functions now looks like this:
```js
module.exports.serialize = (type, value) => {
    if (!(typeof type === "string")) {
        throw "type must be a string"
    }
    const s = new Serializer()
    switch (type) { case "Plant": serialize_PLANT(s, value); break; case "Post": serialize_POST(s, value); break; case "Module": serialize_MODULE(s, value); break; case "ModuleString": serialize_MODULE_STRING(s, value); break; case "Structure": serialize_STRUCTURE(s, value); break; case "StructureBlueprint": serialize_STRUCTURE_BLUEPRINT(s, value); break }
    return s.finish()
}

module.exports.deserialize = (type, bytes) => {
    if (!(typeof type === "string")) {
        throw "type must be a string"
    }
    const d = new Deserializer(bytes)
    switch (type) { case "Plant": return deserialize_PLANT(d); case "Post": return deserialize_POST(d); case "Module": return deserialize_MODULE(d); case "ModuleString": return deserialize_MODULE_STRING(d); case "Structure": return deserialize_STRUCTURE(d); case "StructureBlueprint": return deserialize_STRUCTURE_BLUEPRINT(d) }
}
```
Thank you!
