### ISSUE TITLE
Line separator missing in js/ts output

### ISSUE THREAD

**Issue by Vloz** [teamplayer3/postcard-bindgen#6]
Maybe isolated.

Tried with the basic Test example of the readme, js output is fine until the end of serializer class, then a few `\n` /` ; `are missing.
*.d.ts file do not contains any line separator.

Any idea where it might come from?

```
// Previous code is fine
const serialize_FOO = (s, v) => {
    s.serialize_number(U8_BYTES, false, v.name);
    s.serialize_number(U16_BYTES, false, v.other)
} const deserialize_FOO = (d) => ({ name: d.deserialize_number(U8_BYTES, false), other: d.deserialize_number(U16_BYTES, false) }) const is_FOO = (v) => (typeof v === "object" && typeof v.name === "number" && typeof v.other === "number") module.exports.serialize = (type, value) => {
    if (!(typeof type === "string")) { throw "type must be a string" } const s = new Serializer() switch (type) {
        case "FOO": if (is_FOO(value)) { serialize_FOO(s, value) } else throw "value has wrong format";
            break
    } return s.finish()
} module.exports.deserialize = (type, bytes) => { if (!(typeof type === "string")) { throw "type must be a string" } const d = new Deserializer(bytes) switch (type) { case "FOO": return deserialize_FOO(d) } }
```

Everything works fine once linebreak are added manually.

**Comment by teamplayer3** [comment]
Tried to fix it in 91faf79d8f1ebef108dcc6ceaa640e0c44de239a. Can you check?

**Comment by Vloz** [comment]
> 

Doesnt seems work, from 6 to 6 linebreak missing in the readme example.
The function is being call 3times but the output has no linebreak (in the issue post i added manually some for visibility, but output is always one line).

Had also difficulties with mid range number (like timestamp) which seems to led to incorrect parses. (maybe because i pass the message as Uint8Array rather than a number[]).

(Went to asm deserializer for the moment, crazy easy to implement with wasm-bindgen + tsify).

**Comment by Vloz** [comment]
> Have you used the state of the main branch for testing it again?

Couldn't build with `postcard-bindgen = { git = "https://github.com/teamplayer3/postcard-bindgen", branch = "main" }`, cargo acted like no function were exposed (except PostcardBindings macro).
So i edited the original crate (from .cargo/registry) and add a println! right before it + Cargo clean to be sure modification were taken into account.
That how i can tell the function is being call 3times with the readme example, yet the output is still 1line.


> 
> I will check the Uint8Array thing. Can you give an example on how you pass the timestamp?


```
const data : ArrayBuffer = await (e.data as Blob).arrayBuffer(); //received data from websocket
const message = PsBindGenMessage.deserialize("SocketMessage", new Uint8Array(data) as unknown as number[]);
```

u32 value worked fine at value like 100 and 2^16+1, yet at some point i didn't try to figure the value is wrongly parsed and next fields are returned as undefined.
The same Uin8Array works fine when loaded from wasm postcard.

```
let status_code = StatusCode::Error { detail: String::from("Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(ExitStatus(101))):") };

let message = SocketMessage::Status {
    code: status_code, //enum with string, works fine
    start_time: 6_000_000, //u64, Fail with this value, works with 100 or 65537
    mem: 100, // here and below will turn undefined if the value above fail
    xtime: 100,
    live_uploads: 100,
};` 

```

**Comment by teamplayer3** [comment]
> postcard-bindgen = { git = "https://github.com/teamplayer3/postcard-bindgen", branch = "main" }

You have to pass the feature `generating`. This feature enables all the generating stuff. This is used to allow the macro derives in `no_std` crates and generate the bindings in another crate. Look at `examples/no_std`.

Could you run the example `small` with `cargo run --example small --features=std,generating`? This should work.

**Comment by Vloz** [comment]
> You have to pass the feature `generating`. This feature enables all the generating stuff.
 Sorry, build it again from git this time and still one line output.

> Could you run the example `small` with `cargo run --example small --features=std,generating`? This should work.
Same result.

**Comment by teamplayer3** [comment]
Could you print the generated string with `println!("{:?}", generate_bindings!(Test).js_file.as_str());` in your project? This should show the line endings. I'm a little confused why it outputs without line breaks.

**Comment by Vloz** [comment]
> Could you print the generated string with `println!("{:?}", generate_bindings!(Test).js_file.as_str());` in your project? This should show the line endings. I'm a little confused why it outputs without line breaks.

There is only one \n at the very end of the &str.
If this is an isolated issue we d rather close it for the moment (until somebody with more insight face it).

**Comment by teamplayer3** [comment]
Can you try it with rust nightly. https://github.com/udoprog/genco/issues/29

**Comment by Vloz** [comment]
> Can you try it with rust nightly. [udoprog/genco#29](https://github.com/udoprog/genco/issues/29)

**Works! Both 0.2.0 and 0.3.0 output correctly formatted js once project to nightly.** 



> Can you recheck your whole project with the latest state on main? Now it should support large integers.

Couldn't use my initial code with 0.3.0.
Still get parse with wrong and undefined value in 0.2.0, but with 0.3.0 throw me "variant not implemented" with [0, 197, 237, 230, 184, 252, 48, 128, 224, 177, 3, 100, 0] that is supposed to be "Status" with the following model:
![image](https://user-images.githubusercontent.com/2368643/235112459-c99179f9-ccfc-4d97-a3de-3de6699dbc15.png)


Back in 0.2.0 the enum was correctly recognize:
![image](https://user-images.githubusercontent.com/2368643/235111568-98db780f-3114-4a6c-8dbe-4a34c8eeaf81.png)

**Comment by teamplayer3** [comment]
I checked your code example. If I serialize the message with postcard 

```rust
postcard::to_vec::<_, 20>(&SocketMessage::Status {
            code: StatusCode::Starting,
            start_time: 12_123_123,
            mem: 100,
            cpu: 6_000,
            live_uploads: 0
        })
        .unwrap()
```
 I get `[0, 0, 243, 247, 227, 5, 100, 240, 46, 0]`. If I deserialize the bytes in JavaScript again, I get the correct values:

```js
{
  tag: 'Status',
  value: {
    code: { tag: 'Starting' },
    start_time: 12123123,
    mem: 100,
    cpu: 6000,
    live_uploads: 0
  }
}
```

Bytes interpreted:

```
[ 
  0,  <-- outer enum variant (Status)
  0, <-- enum StatusCode (Starting)
  243, 247, 227, 5,  <-- start_time
  100, <-- mem
  240, 46, <-- cpu 
  0 <-- live_uploads
]
```

Fixed braces, but this shouldn't be an issue. Can you check it again?

**Comment by Vloz** [comment]
Sorry just figure out i was in 0.2.0 gain... FFS 😣

**Comment by Vloz** [comment]
Everything is working fine with 0.3.0 and nightly! 🙏
Thank you very much for the help and sorry for the incorrect report. 🤕

**Comment by teamplayer3** [comment]
No problem. Thank you for reporting and helping to fix some bugs💪 do you stick with wasm-bindgen or do you use this crate now? It would be interesting to have some benchmarks in comparison to the wasm-bindgen solution.

**Comment by Vloz** [comment]
> do you stick with wasm-bindgen or do you use this crate now?

Hard to choose be honnest.
Could not figure out how to share wasm-bindgen types with my rust app (wasm is compiled as cdylib and macro fail compiling outside of this context). Plus tsify wont support variant enum key/value type as postcard-bidgen does because it need a specific serde macro not allowed by postcard (throwing "wont support" if set). 
Ended up doing copy/past type from one project to the other. 

While i can just put Postcard-bindgen types on a side project, run js generation in the build.rs and share its type with my rust app without any struggle.


But outside of that, wasm-bindgen is more straightforward when used with serde-wasm-bindgen and tsify:

```
#[derive(Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi)]
pub enum SocketMessage {
...
}

#[wasm_bindgen]
pub fn parse_socket_message(bytes: &[u8]) -> SocketMessage {
    postcard::from_bytes::<SocketMessage>(bytes).unwrap()
}
```


> It would be interesting to have some benchmarks in comparison to the wasm-bindgen solution.

Thats a quite limited one... 😋 But for the 10bytes message we tested, sent with randomized u32 values called 1k/s:
|   | Postcard Bindgen  | Wasm |
| ------------- | ------------- | ------------- |
| First 10 calls  | 81µs  | 54µs  |
| Stabilized at 4K  | 25µs  | 20µs  |
|Size              | 10kB raw | 28kB bin|

**Comment by teamplayer3** [comment]
> Could not figure out how to share wasm-bindgen types with my rust app (wasm is compiled as cdylib and macro fail compiling outside of this context). Plus tsify wont support variant enum key/value type as postcard-bidgen does because it need a specific serde macro not allowed by postcard (throwing "wont support" if set).
Ended up doing copy/past type from one project to the other.
While i can just put Postcard-bindgen types on a side project, run js generation in the build.rs and share its structs with my rust app without any struggle.

Thanks for sharing your thoughts. I wrote this crate a while ago to have a small binary on the rust side (derive macros only expand for the crate in which the bindings generate) because I used it for communication with an embedded device and to communicate with a mobile app over bluetooth.

> Thats a quite limited one... 😋 But for the 10bytes message we tested, sent with randomized u32 values called 1k/s:

Ah, very cool. Maybe `pstcard-bindgen` could be a little faster, if not checking the types in JavaScript when using with typescript.

**Comment by teamplayer3** [comment]
Disabled js type checks in branch `no-js-typechecks`. Maybe you can run your benchmark again. But I don't know if it's that much of a difference if the types have few fields.

**Comment by Vloz** [comment]
Sorry just drop a few hours ago the benchmark setup to restore the whole project architecture and kept the wasm solution, all the tests were done within my main project (not using git yet). 🤕
