### ISSUE TITLE
How to handle arrays?

### ISSUE THREAD

**Issue by fuse117** [teamplayer3/postcard-bindgen#7]
First, nice project, and thanks for producing it. 

Would the following be easy to support?  Or is there another way to go about it? 

```rust
#[derive(Serialize, PostcardBindings)]
struct Test {
    name: u8,
    other: u16,
    values: [u32; 32],
}
```

```shell
10 |     values: [u32; 32],
   |             ^^^^^^^^^ the trait `GenJsBinding` is not implemented for `[u32; 32]
```

**Comment by teamplayer3** [comment]
Thanks for asking. I added it with branch `impl-genJsBindgen-for-array`. Could you give it a try?
